### ISSUE TITLE
cannot run with python3.8

### ISSUE THREAD

**Issue by linsite** [eBay/LatentScope#1]
when run `python3 main.py`

got and error:
```TypeError: unsupported operand type(s) for |: 'dict' and 'dict' ```

can be fixed with:

change `for node in pa_scores | ch_scores:` to `for node in {**pa_scores, **ch_scores}:`

**Comment by Eaton18** [comment]
It is recommended to use a higher version of Python, Python 3.8 end of life, last release was 3.8.20, End of support on 2024-10-07, see([https://www.python.org/downloads/release/python-3820/](https://www.python.org/downloads/release/python-3820/))

**Comment by linsite** [comment]
i agree, but the readme recommand >= 3.8, which is outdated.

**Comment by Eaton18** [comment]
thanks, updated readme doc.
